server:
  port: 9095
  servlet:
    context-path: /dekra

spring:
  application:
    name: quickprod
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://${keycloak.domain}/realms/${keycloak.realm}
  datasource:

logging:
  level:
    org:
      springframework:
        web: INFO
      hibernate: INFO

keycloak:
  client-id: auth-service-v1
  client-secret: MLaTjNY5t4KzutqLWNCDoFm7b4pQaTJE
  get-token-url: http://localhost:9090/realms/quickprod-realm/protocol/openid-connect/token
  issuer-url: http://localhost:9090/realms/quickprod-realm
redis:
  config:
    cache:
      host: localhost
      port: 6379
      password: redis-password


