server:
  port: 8888

spring:
  application:
    name: cloud-config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/customer-services
            - classpath:config/fraud-services

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
    enabled: true

management:
  endpoints:
    web:
      exposure:
        include: '*'

