version: '3.6'

services:
  postgres_db:
    container_name: postgres_keycloak_database
    build:
      context: .
      dockerfile: ../Dockerfile-postgres
    restart: always
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: kcadmin
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    networks:
      - keycloak-and-postgres-network
    volumes:
      - postgres_db_data:/var/lib/postgresql/data

  keycloak_web:
    container_name: keycloak_web
    build:
      context: .
      dockerfile: ../Dockerfile-keycloak
    command:
      - start-dev
      - --import-realm
    depends_on:
      - postgres_db
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - ./realm-export/realm-export.json:/opt/keycloak/data/import/realm-export.json
    networks:
      - keycloak-and-postgres-network
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin@123
      KC_DB: postgres
      KC_DB_USERNAME: kcadmin
      KC_DB_PASSWORD: password
      KC_DB_URL: jdbc:postgresql://postgres_db:5432/keycloak
      KC_DB_SCHEMA: public
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      KC_LOG_LEVEL: info
      KC_METRICS_ENABLED: true
      KC_HEALTH_ENABLED: true

networks:
  keycloak-and-postgres-network:

volumes:
  postgres_db_data: